### ISSUE TITLE
There is no newest release for umd

### ISSUE THREAD

**Issue by Antontelesh** [folktale/data.maybe#12]
I have a legacy project to work on. It uses AMD module syntax.
The README says I can download the latest release and use the `.umd.js` file.
But the latest UMD release was `1.0.3`. Can we build UMD with the newest version?

**Comment by robotlolita** [comment]
Ah, I should update the README. The only supported installation method has been npm for a while now.

You can see the instructions to create the UMD bundle yourself here: https://github.com/folktale/data.maybe#compiling-from-source

**Comment by Antontelesh** [comment]
Thanks! Already done that.
