### ISSUE TITLE
A shorter way to construct a Maybe from nullable value

### ISSUE THREAD

**Issue by raine** [folktale/data.maybe#8]
I find `Maybe.fromNullable` useful but quite unwieldily named also.

[Some libraries](https://github.com/ramda/ramda-fantasy/blob/master/src/Maybe.js#L3-L5) allow constructing a Maybe directly, like `Maybe(possiblyNull)`.

Would this make sense in `data.maybe` too?

```ls
# this would be nicer if you could just compose with Maybe
get-sig = (.get-or-else '') . (map prop 'text') . Maybe.from-nullable . find-sig-tag . prop 'tags'
```

**Comment by robotlolita** [comment]
Hmm, you can just alias it: `var maybe = Maybe.fromNullable`, or in LiveScript:

```ls
{ Nothing, Just, fromNullable: maybe } = require 'data.maybe'
```

So I'm not sure it makes much sense to special case this function.

**Comment by raine** [comment]
You're right. `maybe` is a good alias for it.
